/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Provider { 'name' : string, 'category' : string }
export interface Task {
  'id' : bigint,
  'escrowFrozen' : boolean,
  'category' : string,
  'providerName' : string,
  'optionalRating' : [] | [bigint],
  'optionalHandshakeKey' : [] | [bigint],
}
export interface _SERVICE {
  'createTask' : ActorMethod<[string, string], bigint>,
  'generateHandshakeKey' : ActorMethod<[bigint], bigint>,
  'getAllProviders' : ActorMethod<[], Array<Provider>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getProvider' : ActorMethod<[string], Provider>,
  'getProvidersByCategory' : ActorMethod<[], Array<Provider>>,
  'getTasksByCategory' : ActorMethod<[], Array<Task>>,
  'rateTask' : ActorMethod<[bigint, bigint], undefined>,
  'registerProvider' : ActorMethod<[string, string], undefined>,
  'verifyHandshake' : ActorMethod<[bigint, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];