/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Provider = IDL.Record({
  'name' : IDL.Text,
  'category' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'escrowFrozen' : IDL.Bool,
  'category' : IDL.Text,
  'providerName' : IDL.Text,
  'optionalRating' : IDL.Opt(IDL.Nat),
  'optionalHandshakeKey' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'createTask' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'generateHandshakeKey' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'getAllProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getProvider' : IDL.Func([IDL.Text], [Provider], ['query']),
  'getProvidersByCategory' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
  'getTasksByCategory' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'rateTask' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'registerProvider' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'verifyHandshake' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Provider = IDL.Record({ 'name' : IDL.Text, 'category' : IDL.Text });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'escrowFrozen' : IDL.Bool,
    'category' : IDL.Text,
    'providerName' : IDL.Text,
    'optionalRating' : IDL.Opt(IDL.Nat),
    'optionalHandshakeKey' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'createTask' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'generateHandshakeKey' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'getAllProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getProvider' : IDL.Func([IDL.Text], [Provider], ['query']),
    'getProvidersByCategory' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
    'getTasksByCategory' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'rateTask' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'registerProvider' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'verifyHandshake' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };